// SPDX-License-Identifier: MIT
// Copyright (c) 2026 cssBruno

package document

import (
	"bytes"
	"crypto/sha1"
	"encoding/gob"
	"encoding/hex"
	"errors"
	"fmt"
	"math"
	"strconv"
	"strings"
)

// ImageInfo stores parsed image data and PDF object metadata for a registered
// image.
type ImageInfo struct {
	data  []byte  // Raw image data
	smask []byte  // Soft mask, an 8-bit per-pixel transparency mask
	n     int     // Image object number
	w     float64 // Width
	h     float64 // Height
	cs    string  // Color space
	pal   []byte  // Image color palette
	bpc   int     // Bits Per Component
	f     string  // Image filter
	dp    string  // DecodeParms
	trns  []int   // Transparency mask
	scale float64 // Document scale factor
	dpi   float64 // dots per inch found from the image file (PNG only)
	i     string  // SHA-1 checksum of the above values
}

func generateImageID(info *ImageInfo) (string, error) {
	if info == nil {
		return "", errors.New("image info is nil")
	}
	h := sha1.New()
	fields := []any{info.data, info.smask, info.n, info.w, info.h, info.cs,
		info.pal, info.bpc, info.f, info.dp, info.trns, info.scale, info.dpi}
	encoder := gob.NewEncoder(h)
	for _, field := range fields {
		if err := encoder.Encode(field); err != nil {
			return "", err
		}
	}
	return hex.EncodeToString(h.Sum(nil)), nil
}

// GobEncode encodes the receiving image to a byte slice.
func (info *ImageInfo) GobEncode() (buf []byte, err error) {
	fields := []any{info.data, info.smask, info.n, info.w, info.h, info.cs,
		info.pal, info.bpc, info.f, info.dp, info.trns, info.scale, info.dpi}
	w := new(bytes.Buffer)
	encoder := gob.NewEncoder(w)
	for j := 0; j < len(fields) && err == nil; j++ {
		err = encoder.Encode(fields[j])
	}
	if err == nil {
		buf = w.Bytes()
	}
	return
}

// GobDecode decodes the specified byte buffer (generated by GobEncode) into
// the receiving image.
func (info *ImageInfo) GobDecode(buf []byte) (err error) {
	fields := []any{&info.data, &info.smask, &info.n, &info.w, &info.h,
		&info.cs, &info.pal, &info.bpc, &info.f, &info.dp, &info.trns, &info.scale, &info.dpi}
	r := bytes.NewBuffer(buf)
	decoder := gob.NewDecoder(r)
	for j := 0; j < len(fields) && err == nil; j++ {
		err = decoder.Decode(fields[j])
	}

	info.i, err = generateImageID(info)
	return
}

func (info *ImageInfo) validForPDF() error {
	if info == nil {
		return errors.New("image info is nil")
	}
	if info.w <= 0 || info.h <= 0 || math.IsNaN(info.w) || math.IsNaN(info.h) || math.IsInf(info.w, 0) || math.IsInf(info.h, 0) {
		return errors.New("invalid image dimensions")
	}
	switch info.cs {
	case "DeviceGray", "DeviceRGB", "DeviceCMYK":
	case "Indexed":
		if len(info.pal) == 0 || len(info.pal)%3 != 0 {
			return errors.New("invalid indexed image palette")
		}
	default:
		return fmt.Errorf("invalid image color space: %s", info.cs)
	}
	if info.bpc <= 0 || info.bpc > 16 {
		return errors.New("invalid image bits per component")
	}
	switch info.f {
	case "", "FlateDecode", "DCTDecode":
	default:
		return fmt.Errorf("invalid image filter: %s", info.f)
	}
	if info.dp != "" && !validImageDecodeParams(info.dp) {
		return errors.New("invalid image decode parameters")
	}
	return nil
}

func validImageDecodeParams(params string) bool {
	fields := strings.Fields(params)
	if len(fields) != 8 {
		return false
	}
	names := []string{"/Predictor", "/Colors", "/BitsPerComponent", "/Columns"}
	values := make([]int, len(names))
	for i, name := range names {
		if fields[i*2] != name {
			return false
		}
		n, err := strconv.Atoi(fields[i*2+1])
		if err != nil {
			return false
		}
		values[i] = n
	}
	predictor, colors, bitsPerComponent, columns := values[0], values[1], values[2], values[3]
	if predictor < 1 || predictor > 15 {
		return false
	}
	if colors != 1 && colors != 3 && colors != 4 {
		return false
	}
	switch bitsPerComponent {
	case 1, 2, 4, 8, 16:
	default:
		return false
	}
	return columns > 0
}

// Extent returns the width and height of the image in the units of the Document
// object.
func (info *ImageInfo) Extent() (wd, ht float64) {
	return info.Width(), info.Height()
}

// Width returns the width of the image in the units of the Document object.
func (info *ImageInfo) Width() float64 {
	if info == nil {
		return 0
	}
	return info.w / (info.scale * info.dpi / 72)
}

// Height returns the height of the image in the units of the Document object.
func (info *ImageInfo) Height() float64 {
	if info == nil {
		return 0
	}
	return info.h / (info.scale * info.dpi / 72)
}

// SetDpi sets the dots per inch for an image. PNG images may have their DPI set
// automatically if the image specifies it. DPI information is not currently
// available automatically for JPEG, GIF, and WebP images, so callers can set it
// here when it matters. It defaults to 72 DPI.
func (info *ImageInfo) SetDpi(dpi float64) {
	info.dpi = dpi
}
